### PR TITLE
[wip] Add diofant

### PR DESCRIPTION
**Pull request by skirpichev**
replacement for #8

### CODE REVIEW

**Comment by bjodah** [comment]
Thanks, that looks much more manageable.
Since tests are running with conda I added this line to the CI script in #8:
https://github.com/bjodah/sym/pull/8/files#diff-cb1051994868e1ed68af44762e613d2bR12

Is diofant on e.g. `conda-forge`? If so it could be added to `meta.yaml` instead.

**Comment by skirpichev** [comment]
> Thanks, that looks much more manageable.

Yet I can't see Details of errors.  Perhaps, something Lambdify-related (this guessed from commits in #8).

> Is diofant on e.g. conda-forge?

I doubt.  I support myself only standard packaging with setuptools & pip.

**Comment by bjodah** [comment]
I see. Thanks for the PR.

**Comment by bjodah** [comment]
(I don't know why the CI logs are private -- they shouldn't be)

**Comment by skirpichev** [comment]
@bjodah, wait!  CI failing!

**Comment by bjodah** [comment]
@skirpichev, thanks, I thought it was just a matter of adding the `pip install` (I added that commit to master).

But CI is indeed still failing, here is the log (you can't access the drone server, right?):
https://pastebin.com/QDsuL8E5

**Comment by skirpichev** [comment]
> you can't access the drone server, right?

Yep. I can't.  That's why PR was marked as '[wip]'.

> https://pastebin.com/QDsuL8E5

Indeed, some Lambdify stuff is broken.  I suggest you to revert pr meanwhile.

**Comment by bjodah** [comment]
I'll revert it (even though I don't guarantee that master is installable, only releases).
Can you reproduce the errors locally?

**Comment by skirpichev** [comment]
> Can you reproduce the errors locally?

Yes.  Yet there shouldn't be too much difference (wrt sympy), so this is a little surprising.

**Pull request merged**
